version: '3'

services:
  island-pulse:
    ports:
      - "3000:3000"
    depends_on:
      - island-pulse-db
    networks:
      - island-pulse

  island-pulse-db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - "3306"
    ports:
      - "3308:3306"
    volumes:
        - ./sql:/docker-entrypoint-initdb.d
        - mysqldata:/var/lib/mysql
    env_file: .env
    networks:
      - island-pulse

networks:
  island-pulse:

volumes:
  mysqldata:
